http:
  port: 8081
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  admin:
    host: '65.1.2.169'
    paths: '/admin*'
  auth:
    host: '65.1.2.169'
    paths: '/auth*'
  order:
    host: '65.1.2.169'
    paths: '/order*'
  product:
    host: '65.1.2.169'
    paths: '/product*'
  profile:
    host: '65.1.2.169'
    paths: '/profile*'
  otp:
    host: '65.1.2.169'
    paths: '/otp*'
  s3:
    host: '65.1.2.169'
    paths: '/s3*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  authService:
    url: 'http://localhost:5001'
  productService:
    url: 'http://localhost:5002'
  orderService:
    url: 'http://localhost:5003'
  profileService:
    url: 'http://localhost:5004'
  adminService:
    url: 'http://localhost:5005'
  otpService:
    url: 'http://localhost:5006'
  s3Service:
    url: 'http://localhost:5007'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  admin:
    apiEndpoints:
      - admin
    policies:
      - proxy:
          - action:
              serviceEndpoint: adminService
  auth:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
  order:
    apiEndpoints:
      - order
    policies:
      - proxy:
          - action:
              serviceEndpoint: orderService
  product:
    apiEndpoints:
      - product
    policies:
      - proxy:
          - action:
              serviceEndpoint: productService
  profile:
    apiEndpoints:
      - profile
    policies:
      - proxy:
          - action:
              serviceEndpoint: profileService
  otp:
    apiEndpoints:
      - otp
    policies:
      - proxy:
          - action:
              serviceEndpoint: otpService
  s3:
    apiEndpoints:
      - s3
    policies:
      - proxy:
          - action:
              serviceEndpoint: s3Service
